baseURL = "http://pytorn.org/"
languageCode = "en-us"
title = "PyTorn"
theme = "kube"
publishDir = "public"

[params]
    twitter = "pytorn"

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "Faq"
    weight = -100
    url = "/faq/"